name: Backend Blog Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8

        run: |
          flake8 main.py  --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 routes/forms_route.py --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 routes/blogs_route.py --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 routes/login_route.py --count --max-complexity=10 --max-line-length=127 --statistics

  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Build Docker Image
        run: |
          docker build -t backend-blog:development .

      - name: Push Docker Image
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DB: ${{ secrets.MYSQL_DB }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
        run: |
          docker tag backend-blog:development darmajr94/backend-blog:development
          docker push darmajr94/backend-blog:development
